[package]
name = "test-shaders"
version = "0.1.0"
edition = "2024"

[dependencies]
magician-rust = { path = "../magician-rust" }
magician-macros = { path = "../magician-macros" }

[build-dependencies]
magician-rust = { path = "../magician-rust" }
magician-macros = { path = "../magician-macros" }
syn = "2.0.117"
quote = "1"
