[package]
name = "magician-vgpu"
version = "0.1.0"
edition = "2024"

[dependencies]
magician-rust = { path = "../magician-rust" }
magician-vgpu-macros = { path = "./macros" }

getset = "0.1.6"
wgpu = { version = "29.0"}
winit = { version = "0.30", features = ["android-native-activity"] }
anyhow = "1.0.102"
bytemuck = "1.25.0"
