[package]
name = "magician-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
magician-ast = { path = "../magician-ast" }
magician-macros = { path = "../magician-macros" }

syn   = { version = "2", features = ["full", "visit", "extra-traits"] }
quote = "1"
proc-macro2 = "1"
prettyplease = "0.2.37"
glam = { version = "0.33.1", features = ["bytemuck"], public = true }
derive_more = { version = "2.1.1", features = ["full"] }
half = "2.7.1"
ahash = "0.8.12"
naga = { version = "29", features = ["wgsl-in", "wgsl-out"] }
bytemuck = "1.25.0"

[build-dependencies]
syn  = { version = "2", features = ["full", "visit", "extra-traits"] }
