[package]
name = "magician-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
magician-ast = { path = "../magician-ast" }
syn   = { version = "2", features = ["full", "visit", "extra-traits"] }
quote = "1"
proc-macro2 = "1"
prettyplease = "0.2.37"
glam = "0.32.1"
derive_more = { version = "2.1.1", features = ["full"] }
half = "2.7.1"

[build-dependencies]
syn  = { version = "2", features = ["full", "visit", "extra-traits"] }
