[package]
name = "shaders"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
magician-rust = { path = "../../magician-rust" }
magician-macros = { path = "../../magician-macros" }
bytemuck = "1.25.0"

[build-dependencies]
magician-rust = { path = "../../magician-rust" }
